import { browserEngines } from "../../../../tooling/browser-engines.mjs";
const selectedEngines = browserEngines({ chromium, webkit });
import {build,preview} from 'vite';import {chromium,webkit,expect} from '@playwright/test';import {mkdtemp,rm,mkdir,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {resolve} from 'node:path';import {createHash,randomUUID} from 'node:crypto';
const temporary=await mkdtemp(resolve(tmpdir(),'quixi-selection-')),report={ selectedEngines: selectedEngines.map(([name]) => name),status:'running',startedAt:new Date().toISOString(),hosts:[],sourceSha256:{}};let server;
const call=(page,command,args={})=>{return page.evaluate(({command,args})=>Promise.race([window.selectionProof.request(command,args),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Timed out: '+command)),15000))]),{command,args}).then(value=>value);};
const detached=(page,args)=>page.evaluate(args=>{window.selectionProof.request('activate',args).catch(error=>{window.proofError={code:error.code,message:error.message};});},args);
const phase=(page,event)=>page.waitForFunction(event=>window.selectionProof.events().some(item=>item.event===event),event);
const restart=async(page,namespace)=>{await page.evaluate(()=>{window.selectionProof.kill();window.selectionProof.restart();});return call(page,'open',{namespace});};
const activation=(expected,candidate,highWater)=>({operationId:randomUUID(),expected,sourceSyncHighWater:highWater,candidate:{archiveId:candidate,manifestSha256:'a'.repeat(64)},reviewToken:randomUUID(),jobId:randomUUID()});
const rejects=async(action,code)=>{let error;try{await action();}catch(value){error=value;}expect(String(error),'Request must fail').not.toBe('undefined');if(code)expect(String(error)).toContain(code);return String(error);};
const save=async()=>{await mkdir('test-results',{recursive:true});await writeFile('test-results/selection-browser.json',JSON.stringify(report,null,2)+'\n');};
try{const outDir=resolve(temporary,'dist');await build({configFile:false,root:import.meta.dirname,build:{outDir,emptyOutDir:true},logLevel:'warn'});server=await preview({configFile:false,root:import.meta.dirname,build:{outDir},preview:{host:'127.0.0.1',port:4201,strictPort:true},logLevel:'warn'});
for(const [name,engine] of selectedEngines){const profile=resolve(temporary,name),namespace=`selection-proof-${randomUUID()}`,host={name,status:'running',checks:[],timings:[]};report.hosts.push(host);let context=await engine.launchPersistentContext(profile,{headless:true});const visit=async()=>{const page=await context.newPage();await page.goto('http://127.0.0.1:4201/');await page.waitForFunction(()=>!!window.selectionProof);return page;};let committed,pending,last;
try{let a=await visit(),b=await visit();expect(await call(a,'open',{namespace})).toEqual({archiveId:'a',selectionRevision:0});host.coldOpen=await call(a,'timing');expect(await call(a,'admission')).toBe(true);await call(b,'open',{namespace});await call(a,'seed');const source=await call(a,'fixture',{archiveId:'a'});expect(source).toEqual({highWater:10,count:1,integrity:'ok'});
 const first=activation({archiveId:'a',selectionRevision:0},'b',10),race=activation(first.expected,'c',10);const raced=await Promise.allSettled([call(a,'activate',{activation:first}),call(b,'activate',{activation:race})]);expect(raced.filter(value=>value.status==='fulfilled')).toHaveLength(1);let current=await call(a,'read');const winner=raced[0].status==='fulfilled'?first:race;expect(current.selectionRevision).toBe(1);expect((await call(b,'status',{operationId:winner.operationId,payload:winner})).status).toBe('committed');for(const payload of [{...winner,sourceSyncHighWater:11},{...winner,reviewToken:randomUUID()},{...winner,jobId:randomUUID()},{...winner,candidate:{...winner.candidate,manifestSha256:'b'.repeat(64)}},{...winner,expected:{...winner.expected,archiveId:'different'}}])await rejects(()=>call(b,'status',{operationId:winner.operationId,payload}),'different full review payload');host.checks.push('two real worker clients race through one selection gate; one atomic head+receipt wins, 16-request admission enforced, source high-water10 differs from count1, full-payload conflicts rejected');
 await rejects(()=>call(a,'guard',{expected:{archiveId:'a',selectionRevision:0}}),'selection changed');expect((await call(a,'fixture',{archiveId:'a'})).count).toBe(1);
 const back=activation(current,'a',10);await call(a,'activate',{activation:back});current=await call(a,'read');expect(current).toEqual({archiveId:'a',selectionRevision:2});await rejects(()=>call(b,'guard',{expected:{archiveId:'a',selectionRevision:0}}),'selection changed');
 // A real effect enters its source queue/gate before replacement. Replacement sees the new high-water.
 await a.evaluate(expected=>{window.selectionProof.request('guard',{expected,delay:150}).catch(()=>{});},current);await phase(a,'guard-entered');const stale=activation(current,'b',10);await rejects(()=>call(b,'activate',{activation:stale}),'high-water changed');expect((await call(a,'fixture',{archiveId:'a'})).highWater).toBe(11);host.checks.push('stale selection revisions including switch-away/back cannot checkpoint generation; in-flight source write precedes activation and invalidates reviewed high-water');
 const candidateHold=await visit();await call(candidateHold,'open',{namespace});await candidateHold.evaluate(()=>{window.selectionProof.request('holdCandidate',{archiveId:'b'}).catch(()=>{});});await phase(candidateHold,'candidate-held');const held=activation(current,'b',11);await rejects(()=>call(a,'activate',{activation:held}),'Candidate owner');expect((await call(a,'status',{operationId:held.operationId})).status).toBe('failed');await candidateHold.close();
 const invalid=activation(current,'b',11);await rejects(()=>call(a,'activate',{activation:invalid,failValidation:true}),'no longer matches');expect((await call(a,'status',{operationId:invalid.operationId})).status).toBe('failed');expect(await call(a,'read')).toEqual(current);host.checks.push('candidate owner contention and failed fresh candidate validation keep prior selection and meaningful failed intent');
 const full=activation(current,'b',11);await rejects(()=>call(a,'activate',{activation:full,sqlFull:true}));expect(await call(b,'read')).toEqual(current);expect((await call(b,'status',{operationId:full.operationId})).status).not.toBe('committed');expect(await call(b,'integrity')).toBe('ok');host.checks.push('real SQLite page-cap failure rolls back selection and receipt together, preserving integrity');
 if(name==='chromium'){const session=await context.newCDPSession(a),origin='http://127.0.0.1:4201',usage=await session.send('Storage.getUsageAndQuota',{origin});const quotaSize=Math.ceil(usage.usage)+262144;expect(quotaSize).toBeLessThan(32*1024*1024);const worker=a.workers()[0];await worker.evaluate(()=>{globalThis.quotaFailures=[];for(const method of ['write','truncate']){const original=FileSystemSyncAccessHandle.prototype[method];FileSystemSyncAccessHandle.prototype[method]=function(...args){try{return original.apply(this,args);}catch(error){globalThis.quotaFailures.push({name:error.name,method});throw error;}}}});const quota=activation(current,'b',11);try{await session.send('Storage.overrideQuotaForOrigin',{origin,quotaSize});await rejects(()=>call(a,'activate',{activation:quota,pressure:true}));host.quota={usage:usage.usage,quotaSize,failures:await worker.evaluate(()=>globalThis.quotaFailures)};expect(host.quota.failures.some(value=>value.name==='QuotaExceededError')).toBe(true);}finally{await session.send('Storage.overrideQuotaForOrigin',{origin});await session.detach();}await restart(a,namespace);expect(await call(a,'read')).toEqual(current);expect((await call(a,'status',{operationId:quota.operationId})).status).not.toBe('committed');expect(await call(a,'integrity')).toBe('ok');host.checks.push('browser-enforced OPFS quota denies actual writes; after restoring quota/reopen, both selection and receipt rolled back with integrityok');}else host.quota={status:'skipped',reason:'WebKit exposes no equivalent CDP quota override; SQL_FULL rollback is tested separately.'};
 pending=activation(current,'b',11);await detached(a,{activation:pending,hang:'intent'});await phase(a,'intent-durable');await a.evaluate(()=>window.selectionProof.kill());expect((await call(b,'status',{operationId:pending.operationId})).status).toBe('interrupted');expect(await call(b,'read')).toEqual(current);await restart(a,namespace);host.checks.push('actual owner-worker termination after durable intent recovers interrupted, never committed');
 const inTransaction=activation(current,'b',11);await detached(a,{activation:inTransaction,hang:'transaction'});await phase(a,'transaction-open');await a.evaluate(()=>window.selectionProof.kill());expect(await call(b,'read')).toEqual(current);expect((await call(b,'status',{operationId:inTransaction.operationId})).status).toBe('interrupted');expect(await call(b,'integrity')).toBe('ok');await restart(a,namespace);host.checks.push('actual worker termination inside open selection+receipt transaction recovers SQLite rollback journal and prior head');
 committed=activation(current,'b',11);await detached(a,{activation:committed,hang:'reply'});await phase(a,'selection-committed');await a.evaluate(()=>window.selectionProof.kill());let receipt=await call(b,'status',{operationId:committed.operationId,payload:committed});expect(receipt.status).toBe('committed');expect(receipt.receipt.selected).toEqual({archiveId:'b',selectionRevision:3});await restart(a,namespace);const later=activation(receipt.receipt.selected,'c',10);await call(b,'activate',{activation:later});last=await call(b,'read');expect((await call(a,'activate',{activation:committed})).selected).toEqual(receipt.receipt.selected);expect(await call(a,'read')).toEqual(last);await rejects(()=>call(a,'activate',{activation:{...committed,expected:{...committed.expected,selectionRevision:99}}}),'different full review payload');host.checks.push('lost real committed reply remains inspectable/replayable after a later switch without switching back; changed revision conflicts');
 // Sustained bounded generation cadence, including pool opening and pause per checkpoint.
 for(let i=0;i<40;i++){const start=Date.now();await call(a,'guard',{expected:last,text:`checkpoint-${i}`});const roundtripMs=Date.now()-start;host.timings.push({...await call(a,'timing'),roundtripMs});await a.waitForTimeout(20);}
 const summarize=key=>{const values=host.timings.map(value=>value[key]).sort((a,b)=>a-b);return{median:values[Math.floor(values.length/2)],p95:values[Math.floor(values.length*.95)],max:values.at(-1)};};host.cadence={samples:40,minimumSpacingMs:20,openMs:summarize('openMs'),pauseCloseMs:summarize('closeMs'),roundtripMs:summarize('roundtripMs')};expect((await call(a,'fixture',{archiveId:'c'})).count).toBe(41);host.checks.push('40 serialized real fixture generation checkpoints measure per-operation selection pool reopen/pause and guard roundtrip');
 // Leave a durable prepared intent across a complete persistent browser process restart.
 pending=activation(last,'a',50);await detached(a,{activation:pending,hang:'intent'});await phase(a,'intent-durable');
}finally{await context.close();}
context=await engine.launchPersistentContext(profile,{headless:true});try{const page=await visit();expect(await call(page,'open',{namespace})).toEqual(last);expect((await call(page,'status',{operationId:pending.operationId})).status).toBe('interrupted');expect((await call(page,'status',{operationId:committed.operationId})).status).toBe('committed');expect((await call(page,'fixture',{archiveId:'c'})).count).toBe(41);const resumed=await call(page,'activate',{activation:pending});expect(resumed.selected).toEqual({archiveId:'a',selectionRevision:last.selectionRevision+1});expect((await call(page,'status',{operationId:pending.operationId,payload:pending})).status).toBe('committed');host.checks.push('complete browser-process restart preserves head, older receipt and separate fixture history; interrupted intent commits only after explicit same-ID revalidation');expect(await call(page,'damage')).toBe(true);await restart(page,namespace).then(()=>{throw new Error('Damaged catalog reopened writable');},error=>{expect(String(error)).toContain('could not be opened');});await rejects(()=>call(page,'read'),'could not be opened');expect((await call(page,'fixture',{archiveId:'a'})).count).toBe(2);expect((await call(page,'fixture',{archiveId:'c'})).count).toBe(41);host.checks.push('physical SQLite header corruption fails unavailable on repeated opens without writable default rollback or damage to retained fixture databases');const reviewed=await visit(),reviewNamespace=`selection-proof-${randomUUID()}`;await call(reviewed,'open',{namespace:reviewNamespace});await call(reviewed,'seed');let reviewedCurrent={archiveId:'a',selectionRevision:0};
for(const mode of ['throw','return','cancel-before','cancel-throw']){const request=activation(reviewedCurrent,'b',10);await rejects(()=>call(reviewed,'reviewed',{activation:request,mode}),mode.startsWith('cancel')?'cancelled before publication':undefined);expect(await call(reviewed,'read')).toEqual(reviewedCurrent);expect((await call(reviewed,'status',{operationId:request.operationId})).status).toBe('failed');expect(await call(reviewed,'expiredCommit')).toBe(true);}
const doubled=activation(reviewedCurrent,'b',10);const doubledReceipt=await call(reviewed,'reviewed',{activation:doubled,mode:'double'});reviewedCurrent=doubledReceipt.selected;expect(await call(reviewed,'expiredCommit')).toBe(true);expect(reviewedCurrent.selectionRevision).toBe(1);
for(const [mode,target] of [['throw-after','c'],['cancel-after','a']]){const request=activation(reviewedCurrent,target,10),receipt=await call(reviewed,'reviewed',{activation:request,mode});reviewedCurrent=receipt.selected;expect((await call(reviewed,'status',{operationId:request.operationId})).status).toBe('committed');expect(await call(reviewed,'expiredCommit')).toBe(true);}
expect(await call(reviewed,'reviewed',{activation:doubled,mode:'throw'})).toEqual(doubledReceipt);expect(await call(reviewed,'read')).toEqual(reviewedCurrent);host.checks.push('activateReviewed composes with exactly one external candidate lock; callback expires on return/throw, commits once, and preserves receipts through replay and postcommit cleanup/cancellation');host.checks.push('before-publication cancellation and a validator returning without commit leave failed intents and unchanged selection');
const managed=await visit(),legacyPage=await visit(),legacyNamespace=`selection-proof-${randomUUID()}`;await call(managed,'open',{namespace:legacyNamespace});await call(managed,'seed');await call(legacyPage,'open',{namespace:legacyNamespace});const unsafe=activation({archiveId:'a',selectionRevision:0},'b',10);await detached(managed,{activation:unsafe,pause:'intent'});await phase(managed,'intent-paused');
await legacyPage.evaluate(namespace=>{window.legacyProof.request('open',{namespace,archiveId:'a',writeOnAcquire:true}).then(value=>{window.legacyAcquired=value;}).catch(error=>{window.legacyFailure=String(error);});},legacyNamespace);
await legacyPage.waitForFunction(async namespace=>(await navigator.locks.query()).pending.some(lock=>lock.name===`quixi:${namespace}:archive:a:owner`),legacyNamespace);
await call(managed,'resumeProof');expect(await call(legacyPage,'read')).toEqual({archiveId:'b',selectionRevision:1});await legacyPage.waitForFunction(()=>!!window.legacyAcquired||!!window.legacyFailure);expect(await legacyPage.evaluate(()=>window.legacyFailure)).toBeUndefined();expect(await legacyPage.evaluate(()=>window.legacyAcquired.sequence)).toBe(11);expect(await legacyPage.evaluate(()=>window.legacyProof.request('write'))).toEqual({sequence:12});
const refused=activation({archiveId:'b',selectionRevision:1},'c',10);await rejects(()=>call(legacyPage,'refuseUnqualifiedActivation',{activation:refused}),'writer cohort is unqualified');expect((await call(legacyPage,'status',{operationId:refused.operationId})).status).toBe('not_found');expect(await call(legacyPage,'read')).toEqual(refused.expected);host.legacy={negativeFixture:'pre-selection writer reacquired old source owner and wrote after selection changed',sequence:12,refusedStatus:'not_found',observations:await legacyPage.evaluate(()=>window.selectionProof.events().filter(item=>item.event==='compatibility-observation'))};await legacyPage.evaluate(()=>window.legacyProof.request('close'));expect((await call(managed,'fixture',{archiveId:'a'})).count).toBe(3);host.checks.push('real pre-fence worker bypass is reproduced after old-owner release; unqualified rollout refuses activation even when the current source has no observed owner, without claiming lock snapshots certify compatibility');
host.userAgent=await page.evaluate(()=>navigator.userAgent);host.status='passed';await save();}finally{await context.close();}}
report.status='passed';}catch(error){report.status='failed';report.error=String(error?.stack??error);process.exitCode=1;console.error(report.error);}finally{for(const file of ["tooling/browser-engines.mjs", 'packages/storage/src/selection/catalog.ts','packages/storage/tests/selection/worker.ts','packages/storage/tests/selection/legacy-worker.ts','packages/storage/tests/selection/index.ts','packages/storage/tests/selection/run.mjs','packages/storage/sqlite/dist/verification.json','packages/storage/sqlite/dist/sqlite3.wasm']){try{report.sourceSha256[file]=createHash('sha256').update(await readFile(file)).digest('hex');}catch{}}report.finishedAt=new Date().toISOString();await save();await new Promise(resolve=>server?server.httpServer.close(resolve):resolve());await rm(temporary,{recursive:true,force:true});console.log(JSON.stringify({status:report.status,hosts:report.hosts.map(({name,status,checks,cadence})=>({name,status,checks:checks.length,cadence})),error:report.error},null,2));}
