#!/usr/bin/env python3
"""Verify frozen source tensors and emit deterministic FP32-only Arctic .qxmodel v1."""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'reference'))
from fetch import verify, sha256
from tokenizers import Tokenizer
from safetensors import safe_open

MAGIC = b'QXARCTIC'
VERSION = 1
HEADER_SIZE = 128
SECTION_SIZE = 32
TENSOR_SIZE = 96


def ranges(values):
    result = []
    for value in values:
        if result and value == result[-1][1] + 1:
            result[-1][1] = value
        else:
            result.append([value, value])
    return result


def is_cjk(cp):
    return any(a <= cp <= b for a, b in [(0x4e00, 0x9fff), (0x3400, 0x4dbf),
        (0x20000, 0x2a6df), (0x2a700, 0x2b73f), (0x2b740, 0x2b81f),
        (0x2b920, 0x2ceaf), (0xf900, 0xfaff), (0x2f800, 0x2fa1f)])


def unicode_data(source):
    tokenizer = Tokenizer.from_file(str(source / 'tokenizer.json'))
    deleted, mapping, punctuation, pool = [], [], [], bytearray()
    for cp in range(0x110000):
        if 0xd800 <= cp <= 0xdfff:
            continue
        char = chr(cp)
        normalized = tokenizer.normalizer.normalize_str(char)
        if is_cjk(cp):
            normalized = normalized.strip(' ')  # C inserts CJK boundaries directly.
        if not normalized:
            deleted.append(cp)
            continue
        if normalized != char:
            value = normalized.encode('utf-8')
            mapping.append((cp, len(pool), len(value)))
            pool.extend(value)
        split = tokenizer.pre_tokenizer.pre_tokenize_str('a' + char + 'b')
        if len(split) == 3 and split[1][0] == char:
            punctuation.append(cp)
    deletion, punct = ranges(deleted), ranges(punctuation)
    data = bytearray(struct.pack('<8sIIII', b'QXUNIC01', len(deletion), len(mapping), len(punct), len(pool)))
    for a, b in deletion:
        data.extend(struct.pack('<II', a, b))
    for entry in mapping:
        data.extend(struct.pack('<III', *entry))
    for a, b in punct:
        data.extend(struct.pack('<II', a, b))
    data.extend(pool)
    return bytes(data), {'deleted_ranges': len(deletion), 'normalization_mappings': len(mapping),
                         'punctuation_ranges': len(punct), 'utf8_bytes': len(pool)}


def align(value):
    return (value + 63) & ~63


def emit_contract(inventory, vocabulary_hash, unicode_hash):
    def c_hash(value):
        return '{' + ','.join('0x' + value[i:i+2] for i in range(0, 64, 2)) + '}'
    lines = ['/* Generated by compile_model.py --freeze-contract; review changes with PORT_SPEC. */',
             '#ifndef QX_MODEL_CONTRACT_H', '#define QX_MODEL_CONTRACT_H',
             'typedef struct { const char *name; uint32_t dim0, dim1, rank; uint64_t bytes; uint8_t hash[32]; } qx_tensor_contract;',
             f'static const uint8_t qx_source_hash[32] = {c_hash(inventory["checkpoint_sha256"])};',
             f'static const uint8_t qx_vocabulary_hash[32] = {c_hash(vocabulary_hash)};',
             f'static const uint8_t qx_unicode_hash[32] = {c_hash(unicode_hash)};',
             'static const qx_tensor_contract qx_contract[101] = {']
    for tensor in inventory['tensors']:
        shape = tensor['shape']
        lines.append('  {' + json.dumps(tensor['name']) + f', {shape[0]}, {shape[1] if len(shape)>1 else 1}, '
                     f'{len(shape)}, {tensor["elements"] * 4}, ' + c_hash(tensor['sha256']) + '},')
    lines.extend(['};', '#endif', ''])
    (ROOT / 'native/model_contract.h').write_text('\n'.join(lines))


def write_tokenizer(output, vocab, unicode, format_lock):
    vocab_offset = 128
    unicode_offset = align(vocab_offset + len(vocab))
    payload = vocab + bytes(unicode_offset - vocab_offset - len(vocab)) + unicode
    header = struct.pack('<8sIIQQQQQ32s32s8s', b'QXTOKEN1', VERSION, 128,
        128 + len(payload), vocab_offset, len(vocab), unicode_offset, len(unicode),
        bytes.fromhex(format_lock['source_sha256']), hashlib.sha256(payload).digest(), bytes(8))
    artifact = output.with_suffix('.qxtokenizer')
    artifact.write_bytes(header + payload)
    manifest = {**format_lock, 'artifact': artifact.name, 'bytes': artifact.stat().st_size,
                'sha256': sha256(artifact), 'purpose': 'standalone tokenizer; no weights or graph initialization'}
    artifact.with_suffix('.qxtokenizer.json').write_text(json.dumps(manifest, indent=2) + '\n')


def compile_model(source, output, freeze_contract=False):
    lock = verify(source)
    inventory = json.loads((ROOT / 'tests/goldens/tensor-inventory.json').read_text())
    if inventory['checkpoint_sha256'] != lock['files']['model.safetensors']['sha256']:
        raise ValueError('Source/inventory checkpoint mismatch')
    with safe_open(source / 'model.safetensors', framework='numpy') as handle:
        expected = inventory['tensors']
        if sorted(handle.keys()) != [tensor['name'] for tensor in expected]:
            raise ValueError('Tensor inventory mismatch')
        for tensor in expected:
            value = handle.get_tensor(tensor['name'])
            if (list(value.shape) != tensor['shape'] or str(value.dtype) != 'float32' or
                    hashlib.sha256(value.tobytes()).hexdigest() != tensor['sha256']):
                raise ValueError('Tensor verification failure: ' + tensor['name'])
    unicode, unicode_stats = unicode_data(source)
    vocab = (source / 'vocab.txt').read_bytes()
    format_lock = {'version': VERSION, 'source_sha256': inventory['checkpoint_sha256'],
                   'vocabulary_sha256': hashlib.sha256(vocab).hexdigest(),
                   'unicode_sha256': hashlib.sha256(unicode).hexdigest(), 'unicode': unicode_stats}
    frozen = ROOT / 'compiler/format-lock.json'
    if freeze_contract:
        frozen.write_text(json.dumps(format_lock, indent=2) + '\n')
        emit_contract(inventory, format_lock['vocabulary_sha256'], format_lock['unicode_sha256'])
    elif json.loads(frozen.read_text()) != format_lock:
        raise ValueError('Compiler format identity changed; contract review required')
    section_table_end = HEADER_SIZE + 4 * SECTION_SIZE
    tensor_table_offset = align(section_table_end)
    tensor_table_length = len(expected) * TENSOR_SIZE
    weights_offset = align(tensor_table_offset + tensor_table_length)
    cursor, records = weights_offset, []
    for tensor in expected:
        name = tensor['name'].encode('ascii')
        if len(name) >= 64:
            raise ValueError('Tensor name exceeds format limit')
        cursor = align(cursor)
        shape = tensor['shape']
        records.append(struct.pack('<64sQQIIII', name, cursor, tensor['elements'] * 4,
                                   shape[0], shape[1] if len(shape) > 1 else 1, len(shape), 1))
        cursor += tensor['elements'] * 4
    weights_length = cursor - weights_offset
    vocab_offset = align(cursor)
    unicode_offset = align(vocab_offset + len(vocab))
    total = unicode_offset + len(unicode)
    if total > 128 * 1024 * 1024:
        raise ValueError('Package exceeds runtime bound')
    sections = [(1, 0, tensor_table_offset, tensor_table_length, len(expected)),
                (2, 0, weights_offset, weights_length, len(expected)),
                (3, 0, vocab_offset, len(vocab), 30522),
                (4, 0, unicode_offset, len(unicode), 1)]
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=output.parent, delete=False) as file:
        temporary = Path(file.name)
        try:
            file.truncate(total)
            file.seek(HEADER_SIZE)
            for section in sections:
                file.write(struct.pack('<IIQQQ', *section))
            file.seek(tensor_table_offset)
            file.write(b''.join(records))
            with safe_open(source / 'model.safetensors', framework='numpy') as handle:
                for tensor, record in zip(expected, records):
                    offset = struct.unpack_from('<Q', record, 64)[0]
                    file.seek(offset)
                    file.write(handle.get_tensor(tensor['name']).tobytes())
            file.seek(vocab_offset); file.write(vocab)
            file.seek(unicode_offset); file.write(unicode)
            file.flush()
            digest = hashlib.sha256()
            with temporary.open('rb') as contents:
                contents.seek(HEADER_SIZE)
                for chunk in iter(lambda: contents.read(1024 * 1024), b''):
                    digest.update(chunk)
            header = struct.pack('<8sIIQII32s32sQQ16s', MAGIC, VERSION, HEADER_SIZE, total, 4, 1,
                                 bytes.fromhex(inventory['checkpoint_sha256']), digest.digest(),
                                 HEADER_SIZE, 4 * SECTION_SIZE, bytes(16))
            assert len(header) == HEADER_SIZE
            file.seek(0); file.write(header)
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    temporary.replace(output)
    manifest = {**format_lock, 'artifact': output.name, 'bytes': total, 'sha256': sha256(output),
                'payload_sha256': digest.hexdigest(), 'sections': [dict(zip(['type','flags','offset','bytes','count'], s)) for s in sections],
                'precision': 'fp32', 'layout': 'row-major-output-input',
                'compiler_sha256': sha256(Path(__file__))}
    write_tokenizer(output, vocab, unicode, format_lock)
    output.with_suffix('.manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(json.dumps(manifest, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / 'build/source')
    parser.add_argument('--output', type=Path, default=ROOT / 'build/arctic-xs.qxmodel')
    parser.add_argument('--freeze-contract', action='store_true', help='Explicitly regenerate reviewed compiler/runtime contract')
    args = parser.parse_args()
    compile_model(args.source, args.output, args.freeze_contract)
