// Generated by native/gpu_release.py --write; verified by default.
export const KERNEL_HASHES={
  "attention": "3f07b3c79ef2c0de2d741fea21c77e3183dc2cced788a7295338c025d374e44b",
  "baseline": "6671b18619861d88c9cb46ffc7eb72464d975dc028478da18a47a8712d476a18",
  "half": "54222a8a80b836ceb42a5827cccb23ae3b0bc7a802c78d23d422c11d570ae4c8",
  "subgroups": "9b2b0937d7b3911dccfcbeb8d36d373a857a01c6011fe0ba187ba3197cb92151",
  "tiled": "6d5ea4ab0951cc237a5e87802019b5e107bfdd81c822cf7e4971099e64a6e79d"
} as const;
export const RUNTIME_SOURCE_SHA256="9f50b0f32bc0e005e342212189df3c3e210ddc1aa92d09d6108bb94a8955837a";
