[package]
name = "quixi-chat-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
metal = ["quixi-chat-kernels/metal", "quixi-chat-engine/metal"]
metal-kernels = ["metal", "quixi-chat-kernels/metal-kernels", "quixi-chat-engine/metal-kernels"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
futures-util.workspace = true
quixi-chat-kernels = { path = "../quixi-chat-kernels" }
quixi-chat-engine = { path = "../quixi-chat-engine" }
mime_guess.workspace = true
rand.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true

[lints]
workspace = true
