import {StrictMode} from 'react';
import {createRoot} from 'react-dom/client';
import { createIsolatedStorageClient as createStorageClient } from "../../../../../../storage/tests/isolated-client.ts";
import {createWebHost} from '../../../../../../../apps/web/src/host/index.ts';
import {ContentPartView,createContentAccess} from '../../index.ts';
import type {CanonicalMutation,BlobPurpose} from '@quixi/core/contracts';
import type {ContentPart,TextBlob} from '@quixi/core/model';
const storage=createStorageClient({archiveId:'test-rich-content-proof',timeoutMs:60000}),host=createWebHost({destinations:[]}),access=createContentAccess({storage,host});
Object.defineProperty(window,'showSaveFilePicker',{value:undefined,configurable:true});
const id=()=>crypto.randomUUID(),root=createRoot(document.getElementById('root')!);
async function blob(bytes:Uint8Array<ArrayBuffer>,purpose:BlobPurpose){const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(value=>value.toString(16).padStart(2,'0')).join('');const transfer=await storage.request(id(),'beginBlobTransfer',{operationId:id(),purpose,expectedBytes:bytes.length,expectedSha256:hash});for(let offset=0,sequence=0;offset<bytes.length;sequence++){const chunk=bytes.slice(offset,offset+1_048_576),length=chunk.length;await storage.sendChunk({transferId:transfer.transferId,sequence,offset,bytes:chunk,final:offset+length===bytes.length});offset+=length;}await storage.request(id(),'finishBlobTransfer',{operationId:id(),transferId:transfer.transferId,expectedBytes:bytes.length,expectedSha256:hash});return{sha256:hash,byteLength:bytes.length,transferId:transfer.transferId};}
const longText='a'.repeat(16_383)+'🧪 — second section\n'+('Archive text\n'.repeat(10_000));
let longBlob:TextBlob;let all:ContentPart[]=[];
async function seed(){const workspace=await storage.request(id(),'archiveWorkspace',null);const text=await blob(new TextEncoder().encode(longText),'canonical_text');longBlob={sha256:text.sha256,byteLength:text.byteLength,encoding:'utf-8'};const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#337755';ctx.fillRect(0,0,2,2);const png=await new Promise<Blob>(resolve=>canvas.toBlob(value=>resolve(value!),'image/png'));const image=await blob(new Uint8Array(await png.arrayBuffer()),'attachment');
 const threadId=id(),contextId=id(),messageId=id(),attachmentId=id(),missingId=id(),rawObjectId=id(),now=Date.now();
 const markdown='# Rendered heading\n\n**Bold text** and `inline code`.\n\n| a | b |\n| - | - |\n| 1 | 2 |\n\n```js\nconst example = "<script>";\n```\n\nInline $x^2 + y^2$ and display:\n\n$$\\frac{1}{2}$$\n\n<script>window.contentAttack=true</script>\n\n[bad link](javascript:alert(1)) ![remote image](https://example.invalid/tracker.png)\n\n$\\href{javascript:alert(1)}{bad}$\n\n```unknownlang\nconst plain = 1;\n```';
 all=[{id:id(),messageId,order:0,kind:'Text',data:{text:markdown}},{id:id(),messageId,order:1,kind:'Text',data:{textBlob:longBlob}},{id:id(),messageId,order:2,kind:'Image',data:{attachmentId,description:'Synthetic local image'}},{id:id(),messageId,order:3,kind:'File',data:{attachmentId:missingId,description:'Missing synthetic attachment'}},{id:id(),messageId,order:4,kind:'ToolCall',data:{name:'retained_tool',input:{html:'<img src=x onerror=alert(1)>'},providerCallId:'synthetic'}},
  {id:id(),messageId,order:5,kind:'Citation',data:{url:'https://example.com/source?x=1',label:'Example source',sourcePartId:null}},
  {id:id(),messageId,order:6,kind:'Citation',data:{url:'javascript:alert(1)',label:'Unsafe citation',sourcePartId:null}},
  {id:id(),messageId,order:7,kind:'ReasoningMetadata',data:{redacted:true,summary:null}},
  {id:id(),messageId,order:8,kind:'StructuredData',data:{value:{answer:42,html:'<b>bold</b>'}}},
  {id:id(),messageId,order:9,kind:'ProviderArtifact',data:{providerKind:'synthetic.artifact',rawObjectId,locator:'record 0'}},
  {id:id(),messageId,order:10,kind:'Audio',data:{attachmentId:missingId,description:'Missing synthetic audio'}},
  {id:id(),messageId,order:11,kind:'Note',data:{text:'A **note** part'}}];
 const mutation=(kind:CanonicalMutation['kind'],payload:unknown)=>({version:1,operationId:id(),recordedAt:now,kind,payload}) as CanonicalMutation;
 await storage.request(id(),'commit',{transactionId:id(),expectedThreadRevisions:[],stagedBlobIds:[text.transferId,image.transferId],mutations:[mutation('CreateThread',{thread:{id:threadId,workspaceId:workspace.workspaceId,createdAt:now,recordedAt:now,systemPrompt:'',preferredRoute:null,importSourceId:null},context:{id:contextId,threadId,previousId:null,version:1,systemPrompt:'',preferredRoute:null,recordedAt:now},state:{threadId,title:'Content proof',tags:[],pinned:false,archived:false,activeLeafMessageId:null,contextSnapshotId:contextId,routingProfile:null,revision:0}}),mutation('RegisterAttachment',{attachment:{id:attachmentId,availability:'available',filename:'synthetic.png',mimeType:'image/png',sizeBytes:image.byteLength,blobSha256:image.sha256,rawObjectId:null}}),mutation('RegisterAttachment',{attachment:{id:missingId,availability:'missing',filename:'missing.bin',mimeType:'application/octet-stream',sizeBytes:null,blobSha256:null,rawObjectId:null}}),mutation('RegisterRawObject',{rawObject:{id:rawObjectId,availability:'missing',sha256:null,byteLength:null,mediaType:'application/octet-stream',storageRef:null}}),mutation('CreateMessage',{message:{id:messageId,threadId,parentId:null,role:'assistant',createdAt:now,recordedAt:now,generationId:null,editedFromMessageId:null,partCount:all.length,sealed:true},parts:all})]});
 all=(await storage.request(id(),'readMessageParts',{messageId,page:{maxItems:16,maxBytes:900_000,cursor:null}})).items as unknown as ContentPart[];render(all);return {imageHash:image.sha256,longBytes:text.byteLength};
}
function render(parts:ContentPart[]){root.render(<StrictMode>{parts.map(part=><article key={part.id} aria-label={`Part ${part.order}`}><ContentPartView part={part} access={access}/></article>)}</StrictMode>);}
Object.assign(window,{contentTest:{seed,async diagnostics(){return storage.request(id(),'diagnostics',null);},async bound(){const a=await access.openText(longBlob),b=await access.openText(longBlob);let rejected=false;try{await access.openText(longBlob);}catch{rejected=true;}await a.close();await b.close();return rejected;},stress(text:string){render([{id:id(),messageId:id(),order:0,kind:'Text',data:{text}}]);},reset(){render(all);},clear(){render([]);},async close(){root.unmount();await access.dispose();await storage.close();await host.dispose();}}});
