import { browserEngines } from "../../../../../../../tooling/browser-engines.mjs";
const selectedEngines = browserEngines({ chromium, webkit });
import {build,preview} from 'vite';import {chromium,webkit,expect} from '@playwright/test';import {mkdtemp,rm,mkdir,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {resolve} from 'node:path';import {createHash} from 'node:crypto';
const temporary=await mkdtemp(resolve(tmpdir(),'quixi-content-')),report={ selectedEngines: selectedEngines.map(([name]) => name),status:'running',startedAt:new Date().toISOString(),hosts:[],sourceSha256:{}};let server;
try{const outDir=resolve(temporary,'dist');await build({configFile:false,root:import.meta.dirname,build:{outDir,emptyOutDir:true},logLevel:'warn'});server=await preview({configFile:false,root:import.meta.dirname,build:{outDir},preview:{host:'127.0.0.1',port:4197,strictPort:true},logLevel:'warn'});
for(const [name,browser] of selectedEngines){const context=await browser.launchPersistentContext(resolve(temporary,name),{headless:true,acceptDownloads:true,...(name==='chromium'?{permissions:['clipboard-read','clipboard-write']}:{})}),page=await context.newPage(),remote=[];page.on('request',request=>{if(/^https?:/.test(request.url())&&!request.url().startsWith('http://127.0.0.1:4197/'))remote.push(request.url());});const host={name,status:'running',checks:[]};report.hosts.push(host);try{await page.goto('http://127.0.0.1:4197/');await page.waitForFunction(()=>!!window.contentTest);const seeded=await page.evaluate(()=>window.contentTest.seed()),before=await page.evaluate(()=>window.contentTest.diagnostics());
 await expect(page.getByRole('heading',{name:'Rendered heading',exact:true})).toBeVisible();await expect(page.locator('.katex').first()).toBeVisible();expect(await page.locator('a[href^="javascript:"]').count()).toBe(0);expect(await page.evaluate(()=>window.contentAttack)).toBeUndefined();expect(remote).toEqual([]);
 const coloured=page.locator('code.language-js');await expect(coloured.locator('.quixi-token-keyword')).toHaveText('const');await expect(coloured.locator('.quixi-token-string')).toHaveText('"<script>"');expect(await coloured.evaluate(element=>element.textContent)).toBe('const example = "<script>";\n');expect(await page.locator('.quixi-markdown script').count()).toBe(0);
 const plain=page.locator('code.language-unknownlang');await expect(plain).toHaveText('const plain = 1;\n');expect(await plain.locator('.quixi-token').count()).toBe(0);
 const copyBlock=page.getByRole('article',{name:'Part 0',exact:true}).locator('.quixi-code').first();await copyBlock.getByRole('button',{name:'Copy code',exact:true}).click();await expect(copyBlock.getByRole('status')).toHaveText('Copied');
 if(name==='chromium')expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('const example = "<script>";\n');
 host.checks.push('real canonical text renders Markdown, GFM tables, fenced code and locally bundled LaTeX without scripts or remote image fetches','fenced code in a supported language is coloured from lossless bounded tokens while unknown languages stay plain text',`copy code writes the exact block text through the host clipboard capability${name==='chromium'?' and reads back identically':' (write only; this engine gates clipboard reading behind platform UI)'}`);
 const long=page.getByRole('article',{name:'Part 1',exact:true});await long.getByRole('button',{name:'Read from start'}).click();await expect(long.getByText('Bytes 0–16,383',{exact:true})).toBeVisible();await long.getByRole('button',{name:'Read next section'}).click();await expect(long.getByText(/🧪 — second section/).first()).toBeVisible();await long.getByRole('button',{name:'Close text preview'}).click();expect(await page.evaluate(()=>window.contentTest.bound())).toBe(true);host.checks.push('verified OPFS text ranges preserve a four-byte scalar split at16KiB and enforce two held readers');
 const img=page.getByRole('article',{name:'Part 2',exact:true});await img.getByRole('button',{name:'Preview image'}).click();await expect(img.getByRole('img')).toBeVisible();expect(await img.getByRole('img').evaluate(element=>element.naturalWidth)).toBe(2);await img.getByRole('button',{name:'Close image preview'}).click();await img.getByRole('button',{name:'Prepare download'}).click();await expect(img.getByRole('button',{name:'Save prepared file'})).toBeVisible();const download=page.waitForEvent('download');await img.getByRole('button',{name:'Save prepared file'}).click();const file=await download;const hash=createHash('sha256').update(await readFile(await file.path())).digest('hex');expect(hash).toBe(seeded.imageHash);await img.getByRole('button',{name:'Release prepared file'}).click();host.checks.push('canonical attachment bytes pass PNG dimension admission, explicit local preview, staged host save gesture and exact downloaded hash');
 const missing=page.getByRole('article',{name:'Part 3',exact:true});await missing.getByRole('button',{name:'Prepare download'}).click();await expect(missing.getByRole('alert')).toContainText('original bytes are unavailable');await page.getByText('Tool call: retained_tool',{exact:true}).click();await expect(page.getByText('<img src=x onerror=alert(1)>',{exact:false}).last()).toBeVisible();expect(remote).toEqual([]);host.checks.push('missing attachments and tool source remain readable without execution');
 const safe=page.getByRole('article',{name:'Part 5',exact:true});await expect(safe.getByRole('link',{name:'Example source',exact:true})).toHaveAttribute('href','https://example.com/source?x=1');await expect(safe.getByRole('link',{name:'Example source',exact:true})).toHaveAttribute('rel',/noopener/);
 const unsafe=page.getByRole('article',{name:'Part 6',exact:true});await expect(unsafe.getByRole('link')).toHaveCount(0);await expect(unsafe.getByText('Unsafe citation',{exact:true})).toBeVisible();
 await expect(page.getByRole('article',{name:'Part 7',exact:true}).getByText('Reasoning is redacted.',{exact:true})).toBeVisible();
 const structured=page.getByRole('article',{name:'Part 8',exact:true});await structured.getByText('StructuredData',{exact:true}).click();await expect(structured.getByText('"answer": 42',{exact:false})).toBeVisible();expect(await structured.locator('b').count()).toBe(0);
 const artifact=page.getByRole('article',{name:'Part 9',exact:true});await artifact.getByText('Original provider content',{exact:true}).click();await expect(artifact.getByText('"locator": "record 0"',{exact:false})).toBeVisible();await artifact.getByRole('button',{name:'Prepare original download',exact:true}).click();await expect(artifact.getByRole('alert')).toContainText('original source bytes are unavailable');
 const audio=page.getByRole('article',{name:'Part 10',exact:true});await expect(audio.getByText('Audio: Missing synthetic audio',{exact:true})).toBeVisible();await audio.getByRole('button',{name:'Attachment details',exact:true}).click();await expect(audio.getByText(/missing\.bin · missing/)).toBeVisible();
 await expect(page.getByRole('article',{name:'Part 11',exact:true}).locator('strong')).toHaveText('note');expect(remote).toEqual([]);
 host.checks.push('citations link only credential-free HTTP(S) URLs while unsafe citations stay text; redacted reasoning, structured data, provider artifacts and audio attachments render as inert readable records with their original representation reachable and no fetches');
 await page.screenshot({path:`test-results/content-${name}.png`,fullPage:true});
 for(const text of ['['.repeat(8000)+'x'+']'.repeat(8000),'> '.repeat(1000)+'nested','x'.repeat(20000),'$'+String.raw`\def\x{\x}\x`+'$']){const start=Date.now();await page.evaluate(value=>window.contentTest.stress(value),text);await expect(page.getByRole('article',{name:'Part 0',exact:true})).toBeVisible();await page.waitForTimeout(100);expect(Date.now()-start).toBeLessThan(2000);expect(await page.evaluate(()=>document.body.textContent.length)).toBeLessThan(18000);}
 host.checks.push('deep nesting, oversized text and recursive math retain bounded responsive source fallbacks');await page.evaluate(()=>window.contentTest.reset());await page.getByRole('article',{name:'Part 1',exact:true}).getByRole('button',{name:'Read from start'}).click();await expect(page.getByText('Bytes 0–16,383',{exact:true})).toBeVisible();const after=await page.evaluate(()=>window.contentTest.diagnostics());expect(after.syncOperations).toBe(before.syncOperations);await page.evaluate(()=>window.contentTest.clear());await expect(page.getByRole('article')).toHaveCount(0);expect(await page.evaluate(()=>window.contentTest.bound())).toBe(true);await page.evaluate(()=>window.contentTest.close());host.checks.push('display operations leave canonical sync count unchanged and active unmount releases readers');host.status='passed';host.userAgent=await page.evaluate(()=>navigator.userAgent);}finally{await context.close();}}
report.status='passed';}catch(error){report.status='failed';report.error=String(error?.stack??error);process.exitCode=1;}finally{for(const file of ["tooling/browser-engines.mjs", 'packages/app/src/features/content/access.ts','packages/app/src/features/content/ContentPartView.tsx','packages/app/src/features/content/Markdown.tsx','packages/app/src/features/content/markdown-budget.ts','packages/app/src/features/content/highlight.ts','packages/app/src/features/content/image-metadata.ts','package-lock.json'])report.sourceSha256[file]=createHash('sha256').update(await readFile(file)).digest('hex');report.finishedAt=new Date().toISOString();await mkdir('test-results',{recursive:true});await writeFile('test-results/content-browser.json',JSON.stringify(report,null,2)+'\n');await server?.httpServer.close();await rm(temporary,{recursive:true,force:true});console.log(JSON.stringify(report,null,2));}
