import { browserEngines } from "../../../../../../../tooling/browser-engines.mjs";
import { exerciseExtensionReceiver } from './extension-receiver.mjs';
const selectedEngines = browserEngines({ chromium, webkit });
import {build,preview} from 'vite';
import {chromium,webkit,expect} from '@playwright/test';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const workspace=resolve(import.meta.dirname,'../../../../../../..'),temporary=await mkdtemp(resolve(tmpdir(),'quixi-import-panel-')),output=resolve(workspace,'test-results/import-panel-browser.json');
const report={ selectedEngines: selectedEngines.map(([name]) => name),status:'running',startedAt:new Date().toISOString(),hosts:[]};await mkdir(resolve(workspace,'test-results'),{recursive:true});const save=()=>writeFile(output,JSON.stringify(report,null,2)+'\n');let server;await save();
const fixture=resolve(workspace,'packages/importers/tests/fixtures/chatgpt-observed.synthetic.json');
try{
 report.sourceSha256={};for(const file of ["tooling/browser-engines.mjs", 'packages/app/src/features/imports/ImportPanel.tsx','packages/app/src/features/imports/controller.ts','packages/app/src/features/imports/host-files.ts','packages/app/src/features/imports/discard.ts','packages/importers/src/host-report.ts','apps/web/src/host/index.ts','apps/web/src/host/transfers.ts','apps/web/src/host/extension-bridge.ts','packages/core/src/contracts/extension-import.ts','packages/app/src/features/imports/tests/browser/extension-receiver.mjs','packages/storage/src/client/archive.ts','package-lock.json'])report.sourceSha256[file]=createHash('sha256').update(await readFile(resolve(workspace,file))).digest('hex');
 const buildOptions={outDir:resolve(temporary,'dist'),emptyOutDir:true,rollupOptions:{input:resolve(import.meta.dirname,'index.html')}};await build({configFile:false,root:import.meta.dirname,build:buildOptions,logLevel:'warn'});server=await preview({configFile:false,root:import.meta.dirname,build:buildOptions,preview:{host:'127.0.0.1',port:4194,strictPort:true},logLevel:'warn'});
 for(const[name,engine]of selectedEngines){
  const archive=`test-panel-${randomUUID()}`,profile=resolve(temporary,name),host={name,status:'running',checks:[]};report.hosts.push(host);await save();let context=await engine.launchPersistentContext(profile,{headless:true,acceptDownloads:true});let baseThreads=0;
  try{const page=await context.newPage();await page.goto(`http://127.0.0.1:4194/?archive=${archive}`);await expect(page.getByRole('heading',{name:'Import your history'})).toBeVisible();host.userAgent=await page.evaluate(()=>navigator.userAgent);
   await page.getByLabel('Source account label').fill('Personal fixture');const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose JSON or ZIP export'}).click();await(await chooser).setFiles(fixture);await expect(page.getByRole('button',{name:'Import history',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Import history',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Import complete.'})).toBeVisible({timeout:60_000});
   assert.equal((await page.evaluate(()=>window.panelTest.threads())).items.length,1);const handles=await page.evaluate(()=>window.panelTest.handles());assert.equal(handles.selectedHandles,1);assert.equal(handles.releasedHandles,1);host.checks.push('React StrictMode panel selects a real host File, imports through production storage, releases selected handle and shows durable completion');
   await page.getByRole('button',{name:'Review notices'}).click();await expect(page.getByText('An attachment was listed, but its file was not found.',{exact:true})).toBeVisible();host.checks.push('bounded source-specific warning review renders missing and unsupported content notices');
   await page.getByRole('button',{name:'Open conversation'}).click();assert.ok((await page.evaluate(()=>window.panelTest.handles())).openedThread);host.checks.push('conversation action returns the canonical thread ID to host composition');
   await page.getByRole('button',{name:'Prepare import report'}).click();const saveButton=page.getByRole('button',{name:/Save report \(/});await expect(saveButton).toBeVisible();const download=page.waitForEvent('download');await saveButton.click();const file=await download;const path=await file.path();const lines=(await readFile(path,'utf8')).trim().split('\n').map(line=>JSON.parse(line));assert.ok(lines.some(line=>line.type==='import-warning'));host.checks.push('report is streamed into a verified host transfer and saved via a separate user gesture');
   // Plan 04 acceptance in the production panel: repeated import, changed source, lexical usability.
   const counts=async()=>{const value={};for(const collection of ['threads','messages','parts','rawObjects'])value[collection]=(await page.evaluate(collection=>window.panelTest.records(collection),collection)).items.length;return value;};
   const importAgain=async(label,path)=>{const knownRuns=new Set((await page.evaluate(()=>window.panelTest.runs())).items.map(run=>run.runId));await page.getByLabel('Source account label').fill(label);const again=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose JSON or ZIP export'}).click();await(await again).setFiles(path);await expect(page.getByRole('button',{name:'Import history',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Import history',exact:true}).click();let newest;await expect.poll(async()=>{const runs=(await page.evaluate(()=>window.panelTest.runs())).items;newest=runs.find(run=>!knownRuns.has(run.runId))??null;return newest&&['complete','failed','cancelled'].includes(newest.state)?newest.state:null;},{timeout:60_000,message:'new import run did not reach a terminal state'}).not.toBeNull().catch(async error=>{console.error('DEBUG-RUNS',JSON.stringify((await page.evaluate(()=>window.panelTest.runs())).items.map(run=>({runId:run.runId,state:run.state,summary:run.summary}))).slice(0,1500),'PANEL',JSON.stringify(await page.locator('.quixi-imports').innerText()).slice(0,800));throw error;});assert.equal(newest.state,'complete',JSON.stringify(newest));return newest;};
   const before=await counts();
   await importAgain('Personal fixture',fixture);
   const repeated=await counts();
   assert.equal(repeated.threads,before.threads);assert.equal(repeated.messages,before.messages);assert.equal(repeated.parts,before.parts);
   host.repeatImport={before,repeated};
   host.checks.push('importing the same export again for the same account creates no duplicate threads, messages or parts');
   const changed=JSON.parse(await readFile(fixture,'utf8'));const userNode=Object.values(changed[0].mapping).find(node=>node.message?.author?.role==='user');userNode.message.content.parts[0]='Describe a fictional comet in more detail.';
   const changedPath=resolve(temporary,'chatgpt-observed.changed.json');await writeFile(changedPath,JSON.stringify(changed));
   const changedRun=await importAgain('Personal fixture',changedPath);
   const after=await counts();
   host.changedImport={before:repeated,after,changedSha256:createHash('sha256').update(await readFile(changedPath)).digest('hex'),run:changedRun,groups:(await page.evaluate(runId=>window.panelTest.groups(runId),changedRun.runId)).items.map(group=>({state:group.state,report:group.report})),rawObjects:(await page.evaluate(()=>window.panelTest.records('rawObjects'))).items.map(raw=>({sha256:raw.sha256,byteLength:raw.byteLength})),events:(await page.evaluate(()=>window.panelTest.records('events'))).items.map(event=>event.details?.code)};await save();
   assert.equal(after.threads,1);assert.ok(after.messages>before.messages,JSON.stringify(host.changedImport));assert.ok(after.rawObjects>repeated.rawObjects);
   const texts=(await page.evaluate(()=>window.panelTest.records('parts'))).items.map(part=>part.data?.text).filter(Boolean);
   assert.ok(texts.includes('Describe a fictional comet.'));assert.ok(texts.includes('Describe a fictional comet in more detail.'));
   host.checks.push('importing changed source text adds a new sealed revision in the same thread while retaining the original message and raw source');
   // Lexical indexing runs from the worker's idle maintenance timer; wait for it, bounded.
   await expect.poll(async()=>(await page.evaluate(()=>window.panelTest.search('fictional comet'))).items.length,{timeout:60_000,intervals:[500]}).toBeGreaterThanOrEqual(1);
   host.checks.push('imported text is searchable through the lexical index with no provider account and no semantic indexing');
   const malformed=JSON.parse(await readFile(fixture,'utf8'));const malformedNode=Object.values(malformed[0].mapping).find(node=>node.message?.author?.role==='user');malformedNode.message.author.role='widget-bot';malformed[0].conversation_id='malformed-synthetic-conversation';
   const malformedPath=resolve(temporary,'chatgpt-observed.malformed.json');await writeFile(malformedPath,JSON.stringify(malformed));
   const malformedRun=await importAgain('Malformed fixture',malformedPath);assert.equal(malformedRun.state,'complete');
   try{await page.getByRole('button',{name:'Review notices'}).click({timeout:15_000});}catch(error){console.error('DEBUG-PANEL',JSON.stringify(await page.locator('.quixi-imports').innerText()).slice(0,1500));throw error;}await expect(page.getByText('A malformed record was skipped. Its original source is saved and later messages were attached to the nearest valid one.',{exact:true})).toBeVisible();
   host.checks.push('a malformed message record is skipped with a visible notice while the rest of the export imports and its raw source is retained');
   // Plan 11: the page side of the browser-extension transfer with a synthetic in-page sender.
   host.extensionReceiver=await exerciseExtensionReceiver({page,fixtureBytes:await readFile(fixture),host});
   await page.screenshot({path:resolve(workspace,`test-results/import-panel-${name}.png`),fullPage:true});
   baseThreads=(await page.evaluate(()=>window.panelTest.threads())).items.length;await page.getByLabel('Source account label').fill('Pause fixture');const pauseChooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose JSON or ZIP export'}).click();await(await pauseChooser).setFiles(fixture);await page.evaluate(()=>window.panelTest.armPause());await page.getByRole('button',{name:'Import history',exact:true}).click();await page.waitForFunction(()=>window.panelTest.stageHeld());await page.getByRole('button',{name:'Pause import',exact:true}).click();await page.evaluate(()=>window.panelTest.releaseStage());await expect(page.getByRole('status').filter({hasText:'Import paused.'})).toBeVisible();assert.equal((await page.evaluate(()=>window.panelTest.threads())).items.length,baseThreads);host.checks.push('pause during an in-flight actual storage acknowledgment retains hidden progress without publishing a partial thread');await page.evaluate(()=>window.panelTest.close());
  }finally{await context.close();}
  context=await engine.launchPersistentContext(profile,{headless:true,acceptDownloads:true});try{const page=await context.newPage();await page.goto(`http://127.0.0.1:4194/?archive=${archive}`);await expect(page.getByRole('button',{name:/Personal fixture.*complete/}).first()).toBeVisible();await page.getByRole('button',{name:/Personal fixture.*complete/}).first().click();await expect(page.getByRole('heading',{name:'Import details'})).toBeVisible();assert.equal((await page.evaluate(()=>window.panelTest.threads())).items.length,baseThreads);host.checks.push('saved run listing and warning/report access survive an actual browser-process restart');
   await page.getByRole('button',{name:/Pause fixture.*paused/}).click();await page.getByRole('button',{name:'Resume selected import'}).click();await expect(page.getByRole('status').filter({hasText:'Import complete.'})).toBeVisible({timeout:60_000});assert.equal((await page.evaluate(()=>window.panelTest.threads())).items.length,baseThreads+1);host.checks.push('paused import resumes after an actual browser-process restart without a selected File or provider account');
   await page.getByLabel('Source account label').fill('Discard fixture');const discardChooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose JSON or ZIP export'}).click();await(await discardChooser).setFiles(fixture);await page.evaluate(()=>window.panelTest.armPause());await page.getByRole('button',{name:'Import history',exact:true}).click();await page.waitForFunction(()=>window.panelTest.stageHeld());await page.getByRole('button',{name:'Pause import',exact:true}).click();await page.evaluate(()=>window.panelTest.releaseStage());await expect(page.getByRole('status').filter({hasText:'Import paused.'})).toBeVisible();await page.getByRole('button',{name:'Discard unfinished work',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Unfinished work discarded.'})).toBeVisible();assert.equal((await page.evaluate(()=>window.panelTest.threads())).items.length,baseThreads+1);host.checks.push('explicit discard removes unfinished import work while preserving already saved conversations and original files');

   const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose JSON or ZIP export'}).click();await(await chooser).setFiles(fixture);await page.getByLabel('Source account label').fill('Dispose fixture');await page.evaluate(()=>window.panelTest.armPause());await page.getByRole('button',{name:'Import history',exact:true}).click();await page.waitForFunction(()=>window.panelTest.stageHeld());await page.evaluate(()=>window.panelTest.unmount());await page.evaluate(()=>window.panelTest.releaseStage());await page.waitForFunction(async()=>{const handles=window.panelTest.handles(),runs=await window.panelTest.runs();return handles.selectedHandles===handles.releasedHandles&&runs.items.some(run=>run.accountScope==='Dispose fixture'&&run.state==='paused');});assert.equal((await page.evaluate(()=>window.panelTest.threads())).items.length,baseThreads+1);host.checks.push('unmount cancels active import, persists paused progress, releases selected host file and publishes no partial thread');await page.evaluate(()=>window.panelTest.close());
  }finally{await context.close();}host.status='passed';await save();console.log(`${name}: React import panel acceptance passed`);
 }
 report.status='passed';
}catch(error){report.status='failed';report.error=String(error?.stack??error);process.exitCode=1;console.error(report.error);}
finally{report.finishedAt=new Date().toISOString();await save();if(server)await new Promise(resolve=>server.httpServer.close(resolve));await rm(temporary,{recursive:true,force:true});}
