#!/usr/bin/env python3
"""Freeze or verify the bundled WGSL/runtime identity; no network or external publication."""
import argparse
import hashlib
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DIRECTORY=ROOT/'kernels/webgpu/1.0.0'
RUNTIME=['encoder.ts','model.ts','tuning.ts']
def digest(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main(write=False):
    kernels={p.stem:digest(p) for p in sorted(DIRECTORY.glob('*.wgsl'))}
    runtime={name:digest(ROOT/'src/gpu'/name) for name in RUNTIME}
    runtime_hash=hashlib.sha256(json.dumps(runtime,sort_keys=True,separators=(',',':')).encode()).hexdigest()
    manifest={'version':'1.0.0','model_format_version':1,'model_sha256':'e1ef345cd35088b06f70c199f5a4e0311bda5983716ad6a3e7d0a604202efffc',
        'kernels':kernels,'runtime_sources':runtime,'runtime_sha256':runtime_hash,
        'experimental':['subgroups'],'note':'WGSL source distribution; actual driver compilation and optional routes require hardware gates.'}
    identity='// Generated by native/gpu_release.py --write; verified by default.\n'
    identity+='export const KERNEL_HASHES='+json.dumps(kernels,indent=2)+' as const;\n'
    identity+='export const RUNTIME_SOURCE_SHA256='+json.dumps(runtime_hash)+';\n'
    if write:
        (DIRECTORY/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
        (ROOT/'src/gpu/identity.ts').write_text(identity)
    else:
        if json.loads((DIRECTORY/'manifest.json').read_text())!=manifest or (ROOT/'src/gpu/identity.ts').read_text()!=identity:
            raise SystemExit('GPU source distribution changed; review and explicitly freeze its version before use')
    print('Verified GPU source distribution 1.0.0'+(' (updated local freeze)' if write else ''))
if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--write',action='store_true');main(parser.parse_args().write)
