import {useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {createImportController} from './controller.ts';
import type {ImportController,ImportPanelProps} from './controller.ts';
import type {JsonObject} from '@quixi/core/model';
import {useFocusRecovery} from '../accessibility/useFocusRecovery.ts';
import './imports.css';
const sizes=(bytes:number)=>{if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return `${(bytes/1024**2).toFixed(1)} MB`;return `${(bytes/1024**3).toFixed(1)} GB`;};
const phaseNames:Record<string,string>={hashing:'Checking source files',preserving:'Saving content',scanning:'Reading export',normalizing:'Organizing conversations',validating:'Checking import',publishing:'Saving conversations',complete:'Complete',paused:'Paused'};
const warningText:Record<string,string>={attachment_bytes_missing:'An attachment was listed, but its file was not found.',unsupported_part_preserved:'Unrecognized content was kept with its original source.',malformed_record_skipped:'A malformed record was skipped. Its original source is saved and later messages were attached to the nearest valid one.',unsupported_or_empty_content:'This message uses content that is not yet displayed directly. Its original source is saved.',metadata_display_truncated:'A long title or detail was shortened for display. The full source is saved.',parent_inferred_from_export_order:'This export had no branch link for a message. Its listed order was used.',heuristic_thread_identity:'This conversation has no stable source ID. Matching uses its content.',source_message_revision:'A changed source message was saved as a new revision. Its earlier version is kept.',source_text_not_valid_unicode:'Text could not be safely decoded. Its original source was kept.',attachment_size_metadata_mismatch:'A file’s size differs from the export metadata. Its actual size was used.',active_branch_unresolved:'The export’s selected branch was unavailable. You can choose a branch in the conversation.'};
function groupTitle(metadata:JsonObject):string{const fields=metadata.fields as JsonObject|undefined;return String(fields?.title??metadata.name??'Imported source').slice(0,180);}
export function ImportPanel(props:ImportPanelProps){
 const focus=useFocusRecovery();
 const callbacks=useRef(props);callbacks.current=props;
 const controller=useMemo(()=>createImportController({...props,onImportComplete:runId=>callbacks.current.onImportComplete?.(runId)}),[props.storage,props.host,props.archiveId,props.workspaceId]);
 const state=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot),mounted=useRef<ImportController|null>(null);
 const [provider,setProvider]=useState<'openai'|'anthropic'>('openai'),[account,setAccount]=useState('');
 useEffect(()=>{mounted.current=controller;void controller.initialize();return()=>{if(mounted.current===controller)mounted.current=null;queueMicrotask(()=>{if(mounted.current!==controller)void controller.dispose();});};},[controller]);
 const selected=state.selectedRun,progress=state.progress;
 const phase=state.discarding?'':state.busy?(progress?phaseNames[progress.phase]??'Importing':'Starting import'):selected?.state==='complete'?'Complete':selected?.state==='paused'?'Paused':'';
 return <section ref={focus.rootRef} onFocusCapture={focus.onFocusCapture} className="quixi-imports" aria-labelledby="import-title">
  <header><h2 ref={focus.anchorRef} tabIndex={-1} className="focus-anchor" id="import-title">Import your history</h2><p>Bring conversations from ChatGPT or Claude into your local library. Original source files are kept alongside your history.</p></header>
  <form onSubmit={event=>{event.preventDefault();void controller.start(provider,account);}}>
   <div className="import-fields"><label>Provider<select value={provider} disabled={state.busy} onChange={event=>setProvider(event.target.value as typeof provider)}><option value="openai">ChatGPT</option><option value="anthropic">Claude</option></select></label>
   <label>Source account label<input value={account} maxLength={256} disabled={state.busy} onChange={event=>setAccount(event.target.value)} placeholder="For example, personal" aria-describedby="import-account-help"/></label></div>
   <p id="import-account-help" className="import-muted">Use the same label for later exports from the same account.</p>
   <div className="import-actions"><button type="button" disabled={state.busy||state.choosing} onClick={()=>void controller.chooseFile()}>{state.choosing?'Choosing…':'Choose JSON or ZIP export'}</button>{state.selectedFile&&<button type="button" disabled={state.busy} onClick={()=>void controller.clearFile()}>Clear selected file</button>}</div>
   {state.selectedFile&&<p className="import-file">{state.selectedFile.name} <span>{state.selectedFile.byteLength===null?'Size unavailable':sizes(state.selectedFile.byteLength)}</span></p>}
   <dl className="import-estimates"><div><dt>Original file</dt><dd>{state.selectedFile?.byteLength===undefined||state.selectedFile.byteLength===null?'Choose a file':sizes(state.selectedFile.byteLength)}</dd></div><div><dt>Conversation history</dt><dd>Calculated during import</dd></div><div><dt>Attachments</dt><dd>Depends on included files</dd></div><div><dt>Search data</dt><dd>Additional space, calculated separately</dd></div></dl>
   {state.availableBytes!==null&&<p className="import-muted">About {sizes(state.availableBytes)} available on this device.</p>}
   <div className="import-actions"><button type="submit" disabled={state.busy||state.choosing||!state.selectedFile||!account.trim()}>Import history</button>{state.busy&&!state.discarding&&<button type="button" onClick={()=>controller.pause()}>Pause import</button>}</div>
  </form>
  <p className="import-phase" role="status" aria-atomic="true">{phase}</p>
  {state.busy&&!state.discarding&&<div className="import-progress">{progress?.totalBytes!==null&&progress?.totalBytes!==undefined&&<><progress max={Math.max(1,progress.totalBytes)} value={Math.min(progress.processedBytes,progress.totalBytes)} aria-label="Current import step"/><span>{sizes(progress.processedBytes)} of {sizes(progress.totalBytes)}</span></>}{progress&&(progress.messages>0||progress.parts>0)&&<span>{progress.messages} messages and {progress.parts} content items processed in this pass</span>}</div>}
  {state.error&&<p className="import-error" role="alert">{state.error}</p>}{state.notice&&<p className="import-notice" role="status">{state.notice}</p>}
  <section aria-labelledby="saved-imports-title"><h3 id="saved-imports-title">Saved imports</h3><p className="import-muted">Resume from saved progress. If the original file was not fully saved, choose that file again before resuming.</p>
   {state.runs.length===0?<p>No imports on this page.</p>:<ul className="import-runs">{state.runs.map(run=><li key={run.runId}><button type="button" disabled={state.busy||state.reportBusy} aria-pressed={selected?.runId===run.runId} onClick={()=>void controller.selectRun(run.runId)}><span>{String(run.summary.sourceName??(run.provider==='openai'?'ChatGPT import':'Claude import'))}</span><small>{run.accountScope} · {new Date(run.recordedAt).toLocaleString()} · {run.state}</small></button></li>)}</ul>}
   <div className="import-actions"><button type="button" disabled={state.busy} onClick={()=>void controller.loadRuns()}>Refresh imports</button>{state.runsCursor&&<button type="button" disabled={state.busy} onClick={()=>void controller.loadRuns(state.runsCursor)}>Next imports</button>}</div>
  </section>
  {selected&&<section aria-labelledby="import-details-title"><h3 id="import-details-title">Import details</h3><p>{selected.provider==='openai'?'ChatGPT':'Claude'} · {selected.accountScope} · {selected.state}</p>
   {typeof selected.summary.lastMessage==='string'&&<p>{selected.summary.lastMessage}</p>}
   <div className="import-actions">{selected.state!=='complete'&&selected.state!=='cancelled'&&<button type="button" disabled={state.busy||state.choosing} onClick={()=>void controller.resume(selected.runId)}>{typeof selected.summary.discardOperationId==='string'?'Finish discarding unfinished work':'Resume selected import'}</button>}{selected.state!=='complete'&&selected.state!=='cancelled'&&<button type="button" disabled={state.busy||state.reportBusy} onClick={()=>void controller.discard(selected.runId)}>Discard unfinished work</button>}<button type="button" disabled={state.busy||state.reportBusy} onClick={()=>void controller.prepareReport()}>{state.reportBusy?'Preparing report…':'Prepare import report'}</button>{state.report&&<button type="button" onClick={()=>void controller.saveReport()}>Save report ({sizes(state.report.byteLength)})</button>}</div>
   <ul className="import-groups">{state.groups.map(group=><li key={group.groupKey}><strong>{groupTitle(group.metadata)}</strong><span>{group.state==='published'?'Conversation saved':group.state==='skipped'?'Previously imported':group.state==='complete'?'Source saved':group.state==='sealed'||group.state==='staging'?'In progress':group.state}</span><div className="import-actions">{typeof group.report.threadId==='string'&&props.onOpenThread&&<button type="button" onClick={()=>props.onOpenThread!(String(group.report.threadId))}>Open conversation</button>}{typeof group.report.importSourceId==='string'&&<button type="button" disabled={state.busy} onClick={()=>void controller.warnings(group)}>Review notices</button>}</div></li>)}</ul>
   {state.groupsCursor&&<button type="button" disabled={state.busy} onClick={()=>void controller.moreGroups()}>Next sources</button>}
   {state.warningGroup&&<div aria-label="Import notices"><h4>Notices for {groupTitle(state.warningGroup.metadata)}</h4>{state.warnings.length===0?<p>No notices on this page.</p>:<ul>{state.warnings.map(event=><li key={String(event.id)}>{warningText[String((event.details as JsonObject).code)]??'Additional source information was retained in the import report.'}</li>)}</ul>}{state.warningsCursor&&<button type="button" disabled={state.busy} onClick={()=>void controller.warnings(state.warningGroup!,state.warningsCursor)}>Next notices</button>}</div>}
  </section>}
 </section>;
}
