import {useEffect,useMemo,useRef,useState} from 'react';
import type {Attachment,ContentPart,RawObject} from '@quixi/core/model';
import type {ContentAccess,ImagePreview,PreparedContentFile,TextReader,TextSection} from './access.ts';
import {MarkdownText} from './Markdown.tsx';
import {safeContentUrl} from './markdown-budget.ts';
import './content.css';
function PagedSource({text}:{text:string}){const [offset,setOffset]=useState(0);return <div><pre className="quixi-content-source">{text.slice(offset,offset+16_384)}</pre>{text.length>16_384&&<div className="quixi-content-actions"><button disabled={!offset} onClick={()=>setOffset(value=>Math.max(0,value-16_384))}>Previous source section</button><button disabled={offset+16_384>=text.length} onClick={()=>setOffset(value=>value+16_384)}>Next source section</button></div>}</div>;}
/** A canonical part is display data. No content operation edits it or invokes a tool. */
let nextAccessKey=0;
export function ContentPartView({part,access}:{part:ContentPart;access:ContentAccess}){
  const accessKey=useMemo(()=>++nextAccessKey,[access]);
  return <ContentPartBody key={`${part.id}:${accessKey}`} part={part} access={access}/>;
}
function ContentPartBody({part,access}:{part:ContentPart;access:ContentAccess}){
  const [error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[section,setSection]=useState<TextSection|null>(null),[attachment,setAttachment]=useState<Attachment|null>(null),[raw,setRaw]=useState<RawObject|null>(null),[image,setImage]=useState<ImagePreview|null>(null),[file,setFile]=useState<PreparedContentFile|null>(null);
  const operationActive=useRef(false);
  const lifecycle=useRef({alive:true,epoch:0});const reader=useRef<TextReader|null>(null),imageLease=useRef<ImagePreview|null>(null),fileLease=useRef<PreparedContentFile|null>(null);
  useEffect(()=>{lifecycle.current={alive:true,epoch:lifecycle.current.epoch+1};return()=>{lifecycle.current.alive=false;lifecycle.current.epoch++;void reader.current?.close().catch(()=>{});reader.current=null;void imageLease.current?.close().catch(()=>{});imageLease.current=null;void fileLease.current?.close().catch(()=>{});fileLease.current=null;};},[part.id,access]);
  const perform=async(action:(current:()=>boolean)=>Promise<void>)=>{if(operationActive.current)return;operationActive.current=true;const epoch=lifecycle.current.epoch;setBusy(true);setError(null);const current=()=>lifecycle.current.alive&&lifecycle.current.epoch===epoch;try{await action(current);}catch(value){if(current())setError(value instanceof Error?value.message:'Content could not be opened.');}finally{operationActive.current=false;if(current())setBusy(false);}};
  const loadAttachment=async()=>{if(attachment)return attachment;if(!['Image','File','Audio'].includes(part.kind))throw new Error('Part is not an attachment.');const value=await access.attachment((part as Extract<ContentPart,{kind:'Image'|'File'|'Audio'}>).data.attachmentId);return value;};
  const openText=(offset:number)=>perform(async current=>{if(part.kind!=='Text'&&part.kind!=='Note'||!part.data.textBlob)return;if(!reader.current){const opened=await access.openText(part.data.textBlob);if(!current()){await opened.close();return;}reader.current=opened;}const value=await reader.current.read(offset);if(current())setSection(value);});
  const prepare=()=>perform(async current=>{let input:{sha256:string;byteLength:number;filename:string|null;mediaType:string};if(part.kind==='ProviderArtifact'){const value=raw??await access.raw(part.data.rawObjectId);if(current())setRaw(value);if(value.availability!=='available'||!value.sha256||value.byteLength===null)throw new Error('The original source bytes are unavailable.');input={sha256:value.sha256,byteLength:value.byteLength,filename:'original-source.bin',mediaType:value.mediaType};}else{const value=await loadAttachment();if(current())setAttachment(value);if(value.availability!=='available'||!value.blobSha256||value.sizeBytes===null)throw new Error('The attachment was recorded, but its original bytes are unavailable.');input={sha256:value.blobSha256,byteLength:value.sizeBytes,filename:value.filename,mediaType:value.mimeType??'application/octet-stream'};}await fileLease.current?.close();fileLease.current=null;const opened=await access.prepareFile(input);if(!current()){await opened.close();return;}fileLease.current=opened;setFile(opened);});
  const preview=()=>perform(async current=>{const value=await loadAttachment();if(current())setAttachment(value);await imageLease.current?.close();imageLease.current=null;const opened=await access.openImage(value);if(!current()){await opened.close();return;}imageLease.current=opened;setImage(opened);});
  let body;
  if(part.kind==='Text'||part.kind==='Note')body=part.data.textBlob?<><p>Long {part.kind.toLowerCase()} · {part.data.textBlob.byteLength.toLocaleString()} bytes</p><button disabled={busy} onClick={()=>void openText(0)}>Read from start</button>{section&&<><MarkdownText text={section.text} clipboard={{state:access.clipboard,copy:access.copyText}}/><p>Bytes {section.offset.toLocaleString()}–{(section.nextOffset??section.totalBytes).toLocaleString()}</p>{section.nextOffset!==null&&<button disabled={busy} onClick={()=>void openText(section.nextOffset!)}>Read next section</button>}<button disabled={busy} onClick={()=>void perform(async()=>{await reader.current?.close();reader.current=null;setSection(null);})}>Close text preview</button></>}</>:<MarkdownText text={part.data.text??''} clipboard={{state:access.clipboard,copy:access.copyText}}/>;
  else if(part.kind==='Citation'){const url=safeContentUrl(part.data.url??undefined);body=<p>{url?<a href={url} target="_blank" rel="noreferrer noopener">{part.data.label??url}</a>:part.data.label??'Citation without an available web link'}</p>;}
  else if(part.kind==='Image'||part.kind==='File'||part.kind==='Audio')body=<><p>{part.kind}: {part.data.description??attachment?.filename??'Attachment retained in your archive'}</p>{attachment&&<p>{attachment.filename??'Unnamed attachment'} · {attachment.availability} · {attachment.sizeBytes===null?'Unknown size':`${attachment.sizeBytes.toLocaleString()} bytes`}</p>}<div className="quixi-content-actions"><button disabled={busy} onClick={()=>void perform(async current=>{const value=await loadAttachment();if(current())setAttachment(value);})}>Attachment details</button>{part.kind==='Image'&&<button disabled={busy} onClick={()=>void preview()}>Preview image</button>}<button disabled={busy} onClick={()=>void prepare()}>Prepare download</button></div>{image&&<figure><img src={image.url} onError={()=>{const failed=imageLease.current;imageLease.current=null;setImage(null);setError("The image bytes could not be decoded. You can still save the original.");void failed?.close().catch(()=>{});}} alt={part.data.description??attachment?.filename??'Archived image'} width={image.width} height={image.height}/><button onClick={()=>void perform(async()=>{await imageLease.current?.close();imageLease.current=null;setImage(null);})}>Close image preview</button></figure>}</>;
  else if(part.kind==='ReasoningMetadata')body=<p>{part.data.redacted?'Reasoning is redacted.':part.data.summary??'Reasoning metadata retained.'}</p>;
  else body=<details><summary>{part.kind==='ProviderArtifact'?'Original provider content':part.kind==='ToolCall'?`Tool call: ${part.data.name}`:part.kind==='ToolResult'?'Tool result (not executed)':part.kind}</summary><PagedSource text={JSON.stringify(part.data,null,2)}/>{part.kind==='ProviderArtifact'&&<><p>This is retained provider data. Opening it does not execute it. The download contains its full original blob; the locator identifies the relevant record.</p><button disabled={busy} onClick={()=>void prepare()}>Prepare original download</button></>}</details>;
  return <div className="quixi-content-part">{body}{file&&<div className="quixi-content-actions"><p>{file.filename} · {file.byteLength.toLocaleString()} bytes ready</p><button disabled={busy} onClick={()=>void perform(async()=>{await file.save();})}>Save prepared file</button><button disabled={busy} onClick={()=>void perform(async()=>{await fileLease.current?.close();fileLease.current=null;setFile(null);})}>Release prepared file</button></div>}{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Opening content…</p>}</div>;
}
